// Autogenerated by catalog_gen.go.  Do not modify.
package govee

// Kind is a representation of the type of device.  Devices are
// broken into types like "String Lights" or "Strip Lights".
type Kind string

// Spec hosts specific device information.
type Spec struct {
	Kind       Kind   // device type
	SKU        string // device SKU
	Name       string // device Name
	ProductURL string // url to product page
}

const (
	FloorLamps        Kind = "Floor Lamps"
	LandscapeLighting Kind = "Landscape Lighting"
	RGBICStripLights  Kind = "RGBIC Strip Lights"
	RGBStripLights    Kind = "RGB Strip Lights"
	StringLights      Kind = "String Lights"
	StripLights       Kind = "Strip Lights"
	TVBackLights      Kind = "TV BackLights"
	TableLamps        Kind = "Table Lamps"
	WallLights        Kind = "Wall Lights"
)

var catalog = []Spec{
	{FloorLamps, "H6072", "Govee RGBICWW Floor Lamp", "https://app-mall.govee.com/product-detail?sku=H6072182"},
	{FloorLamps, "H6073", "Smart RGB LED floor lamp", ""},
	{FloorLamps, "H6076", "Govee RGBICW Floor Lamp Basic", "https://app-mall.govee.com/product-detail?sku=H6076182"},
	{FloorLamps, "H6078", "Govee RGBICWW Cylinder Floor Lamp", "https://app-mall.govee.com/product-detail?sku=H6078102"},
	{FloorLamps, "H607C", "Govee RGBICWW Floor Lamp 2", "https://app-mall.govee.com/product-detail?sku=H607C111"},
	{LandscapeLighting, "H7050", "Smart Ground Lights", ""},
	{LandscapeLighting, "H7051", "Smart Ground Lights", "https://app-mall.govee.com/product-detail?sku=H7051111"},
	{LandscapeLighting, "H7052", "15m Outdoor Ground Lights", "https://app-mall.govee.com/product-detail?sku=H7052111"},
	{LandscapeLighting, "H7053", "30m Outdoor Ground Lights", "https://app-mall.govee.com/product-detail?sku=H7053111"},
	{LandscapeLighting, "H7055", "Govee RGBIC Path Lights", "https://app-mall.govee.com/product-detail?sku=H7055111"},
	{LandscapeLighting, "H705A", "30m Permanent Outdoor Lights", "https://app-mall.govee.com/product-detail?sku=H705A1D1"},
	{LandscapeLighting, "H705B", "15m Permanent Outdoor Lights", "https://app-mall.govee.com/product-detail?sku=H705B1D1"},
	{LandscapeLighting, "H705C", "45m Permanent Outdoor Lights", "https://app-mall.govee.com/product-detail?sku=H705C111"},
	{LandscapeLighting, "H705D", "15m Permanent Outdoor Lights 2", ""},
	{LandscapeLighting, "H705E", "30m Permanent Outdoor Lights 2", ""},
	{LandscapeLighting, "H705F", "45m Permanent Outdoor Lights 2", ""},
	{LandscapeLighting, "H7060", "Govee RGBIC Flood lights", "https://app-mall.govee.com/product-detail?sku=H7060112"},
	{LandscapeLighting, "H7061", "2 Pack RGBIC Flood Lights", ""},
	{LandscapeLighting, "H7062", "6 Pack RGBIC Flood Lights", "https://app-mall.govee.com/product-detail?sku=H7062111"},
	{LandscapeLighting, "H7063", "Govee Outdoor Flood Light", "https://app-mall.govee.com/product-detail?sku=H7063111"},
	{LandscapeLighting, "H7065", "Govee RGBIC Spotlights", ""},
	{LandscapeLighting, "H7066", "Govee RGBIC Spotlights", "https://app-mall.govee.com/product-detail?sku=H7066111"},
	{LandscapeLighting, "H706A", "30m Permanent Outdoor Lights Pro", "https://app-mall.govee.com/product-detail?sku=H706A101"},
	{LandscapeLighting, "H706B", "45m Permanent Outdoor Lights Pro", "https://app-mall.govee.com/product-detail?sku=H706B101"},
	{LandscapeLighting, "H706C", "60m Permanent Outdoor Lights Pro", ""},
	{LandscapeLighting, "H7075", "Govee Outdoor Wall light", "https://app-mall.govee.com/product-detail?sku=B70751D1"},
	{LandscapeLighting, "H70B1", "1.5*2m 520LED Curtain Lights", "https://app-mall.govee.com/product-detail?sku=H70B11A1"},
	{LandscapeLighting, "H70BC", "400LED Curtain Lights", ""},
	{LandscapeLighting, "H805A", "30m Permanent Outdoor Lights Elite", ""},
	{LandscapeLighting, "H805B", "15m Permanent Outdoor Lights Elite", ""},
	{LandscapeLighting, "H805C", "45m Permanent Outdoor Lights Elite", ""},
	{RGBStripLights, "H6110", "2*5m MultiColor with Alexa", ""},
	{RGBStripLights, "H6141", "5m Smart MultiColor  Strip Light", ""},
	{RGBStripLights, "H6159", "5m MultiColor with Alexa", ""},
	{RGBStripLights, "H615A", "5m RGB Strip Light with Alexa", ""},
	{RGBStripLights, "H615B", "10m RGB Strip Light with Alexa", ""},
	{RGBStripLights, "H615C", "15m RGB Strip Light with Alexa", ""},
	{RGBStripLights, "H615D", "20m RGB Strip Light with Alexa", ""},
	{RGBStripLights, "H615E", "30m RGB Strip Light with Alexa", ""},
	{RGBICStripLights, "H6117", "2*5m RGBIC with Alexa", ""},
	{RGBICStripLights, "H6143", "5m RGBIC Strip Light", ""},
	{RGBICStripLights, "H6144", "2*5m RGBIC Strip Light", ""},
	{RGBICStripLights, "H6163", "5m RGBIC with Alexa", ""},
	{RGBICStripLights, "H618A", "5m RGBIC Basic Strip Lights with Alexa", "https://app-mall.govee.com/product-detail?sku=H618A1D1"},
	{RGBICStripLights, "H618C", "10m RGBIC Basic Strip Lights with Alexa", "https://app-mall.govee.com/product-detail?sku=H618C1D1"},
	{RGBICStripLights, "H618E", "2*10m RGBIC Strip Lights with Alexa", "https://app-mall.govee.com/product-detail?sku=H618E1D1"},
	{RGBICStripLights, "H618F", "2*15m RGBIC LED Strip Light With Alexa", "https://app-mall.govee.com/product-detail?sku=H618F1D1"},
	{RGBICStripLights, "H619A", "5m RGBIC Pro Strip Lights with Alexa", ""},
	{RGBICStripLights, "H619B", "7.5m RGBIC Pro Strip Lights with Alexa", ""},
	{RGBICStripLights, "H619C", "10m RGBIC Pro Strip Lights with Alexa", "https://app-mall.govee.com/product-detail?sku=H619C1D1"},
	{RGBICStripLights, "H619D", "2*7.5m RGBIC Pro Strip Lights with Alexa", ""},
	{RGBICStripLights, "H619E", "2*10m RGBIC Pro Strip Lights with Alexa", ""},
	{RGBICStripLights, "H619Z", "3m RGBIC Pro Strip Lights with Alexa", ""},
	{RGBICStripLights, "H61A0", "3m RGBIC LED Neon Rope Lights", "https://app-mall.govee.com/product-detail?sku=H61A01D1"},
	{RGBICStripLights, "H61A1", "2m RGBIC LED Neon Rope Lights", "https://app-mall.govee.com/product-detail?sku=H61A11D1"},
	{RGBICStripLights, "H61A2", "5m RGBIC LED Neon Rope Lights", "https://app-mall.govee.com/product-detail?sku=H61A21D1"},
	{RGBICStripLights, "H61A3", "4m RGBIC LED Neon Rope Lights", ""},
	{RGBICStripLights, "H61A5", "10m RGBIC LED Neon Rope Lights", "https://app-mall.govee.com/product-detail?sku=H61A51D1"},
	{RGBICStripLights, "H61A8", "10m RGBIC Outdoor Neon Rope Light", "https://app-mall.govee.com/product-detail?sku=H61A81D1"},
	{RGBICStripLights, "H61A9", "20m RGBIC Outdoor Neon Rope Light", ""},
	{RGBICStripLights, "H61B1", "5m RGBICW LED Strip Light with cover", ""},
	{RGBICStripLights, "H61BA", "5m RGBICW LED Strip Light", "https://app-mall.govee.com/product-detail?sku=H61BA1D1"},
	{RGBICStripLights, "H61BC", "10m RGBICW LED Strip Light", "https://app-mall.govee.com/product-detail?sku=H61BC1D1"},
	{RGBICStripLights, "H61BE", "2*10m RGBICW LED Strip Light", "https://app-mall.govee.com/product-detail?sku=H61BE1D1"},
	{RGBICStripLights, "H61C2", "2m RGBIC Neon Rope Light for desks", ""},
	{RGBICStripLights, "H61C3", "3m RGBIC Neon Rope Light for gaming desk", "https://app-mall.govee.com/product-detail?sku=H61C31D1"},
	{RGBICStripLights, "H61C5", "5m RGBIC Neon Rope Light for desks", "https://app-mall.govee.com/product-detail?sku=H61C51D1"},
	{RGBICStripLights, "H61E0", "Govee LED Strip Light M1", "https://app-mall.govee.com/product-detail?sku=H61E01D1"},
	{RGBICStripLights, "H61E1", "Govee LED Strip Light M1", "https://app-mall.govee.com/product-detail?sku=H61E11D2"},
	{StringLights, "H7012", "LED Bulb String Lights", ""},
	{StringLights, "H7013", "LED Bulb String Lights", ""},
	{StringLights, "H7021", "LED Bulb String Lights", "https://app-mall.govee.com/product-detail?sku=H70211B1"},
	{StringLights, "H7028", "LED Bulb String Lights", ""},
	{StringLights, "H7033", "LED Bulb String Lights", "https://app-mall.govee.com/product-detail?sku=H70331B1*2"},
	{StringLights, "H7041", "LED Bulb String Lights", ""},
	{StringLights, "H7042", "LED Bulb String Lights", ""},
	{StripLights, "H616C", "10m RGBIC Outdoor Strip Lights 2", ""},
	{StripLights, "H616D", "2*7.5m RGBIC Outdoor Strip Lights 2", ""},
	{StripLights, "H616E", "2*10m RGBIC Outdoor Strip Lights 2", ""},
	{StripLights, "H6172", "10m Outdoor RGBIC LED Strip Lights", ""},
	{StripLights, "H6173", "2*10m Outdoor RGBIC LED Strip Lights", "https://app-mall.govee.com/product-detail?sku=H61761D1"},
	{StripLights, "H6175", "10m RGBIC Outdoor Strip Lights", ""},
	{StripLights, "H6176", "30m RGBIC Outdoor Strip Lights", ""},
	{StripLights, "H70C1", "10m RGBIC String Light", "https://app-mall.govee.com/product-detail?sku=H70C11D1"},
	{StripLights, "H70C2", "20m RGBIC String Light", "https://app-mall.govee.com/product-detail?sku=H70C21D1"},
	{TVBackLights, "H6167", "2.4m RGBIC TV Backlight", ""},
	{TVBackLights, "H6168", "2*0.7m+2*1.2m RGBIC TV Backlight", ""},
	{TVBackLights, "H6182", "Wi-Fi MultiColor TV Strip Light", ""},
	{TVBackLights, "H61B2", "3m RGBIC Neon TV Backlight", ""},
	{TableLamps, "H6042", "Govee TV Light Bar 2", ""},
	{TableLamps, "H6043", "Govee TV Light Bars 2", ""},
	{TableLamps, "H6046", "Govee RGBIC TV Light Bars", "https://app-mall.govee.com/product-detail?sku=H6046101"},
	{TableLamps, "H6047", "Govee RGBIC Gaming Light Bars", "https://app-mall.govee.com/product-detail?sku=H6047181"},
	{TableLamps, "H6051", "Govee Table Lamp Lite", ""},
	{TableLamps, "H6052", "Govee RGBICWW Table Lamp", ""},
	{TableLamps, "H6056", "Govee RGBICWW Light Bars", "https://app-mall.govee.com/product-detail?sku=H60561D1"},
	{TableLamps, "H6059", "Govee Night Light Mini", ""},
	{WallLights, "H6061", "Govee Glide Hexa Light Panels", "https://app-mall.govee.com/product-detail?sku=B6061101"},
	{WallLights, "H6062", "Govee Glide wall light", "https://app-mall.govee.com/product-detail?sku=B6062102"},
	{WallLights, "H6063", "Govee Gaming Wall Light", ""},
	{WallLights, "H6065", "Govee Glide Y Lights", "https://app-mall.govee.com/product-detail?sku=H6065101"},
	{WallLights, "H6066", "Govee Glide Hexa Pro Light Panels", "https://app-mall.govee.com/product-detail?sku=H6066102"},
	{WallLights, "H6067", "Govee Glide Tri Light Panels", ""},
	{WallLights, "H606A", "Govee Glide Hexa Light Panel Ultra", "https://app-mall.govee.com/product-detail?sku=H606A181"},
	{WallLights, "H6087", "Govee RGBIC Fixture Lights", ""},
	{WallLights, "H6088", "Govee RGBIC Cube Wall Sconces", "https://app-mall.govee.com/product-detail?sku=H6088101"},
	{WallLights, "H608A", "5m String Downlights", "https://app-mall.govee.com/product-detail?sku=H608A101"},
	{WallLights, "H608B", "3m String Downlights", "https://app-mall.govee.com/product-detail?sku=H608B101"},
	{WallLights, "H608C", "2m String Downlights", ""},
	{WallLights, "H608D", "10m String Downlights", "https://app-mall.govee.com/product-detail?sku=H608D101"},
	{WallLights, "H60A0", "12inch Ceiling Light", ""},
	{WallLights, "H610A", "Govee Glide Lively Wall Light", "https://app-mall.govee.com/product-detail?sku=H610A1D1"},
	{WallLights, "H610B", "Govee Glide Music Wall Light", ""},
}

// LookupBySKU searches the catalog for a device
// matching the given SKU.
func LookupBySKU(sku string) *Spec {
	for _, device := range catalog {
		if device.SKU == sku {
			return &device
		}
	}

	return nil
}

// LookupByKind searches the catalog and returns
// all the devices matching it.
func LookupByKind(kind Kind) []*Spec {
	data := []*Spec{}

	for _, device := range catalog {
		if device.Kind == kind {
			data = append(data, &device)
		}
	}

	if len(data) > 0 {
		return data
	}
	return nil
}
