version: "3"

tasks:
  go:generate:
    desc: Generate Code
    sources:
      - catalog.go
    cmds:
      - go generate

  go:test:
    desc: Run Tests
    cmds:
      - go test ./...

  go:check:
    desc: Run GoLang Checks
    cmds:
      - staticcheck ./...

  go:fmt:
    desc: Run GoLang formatter
    cmds:
      - gofmt ./
