name: Pull Request
on:
  - pull_request

jobs:
  test:
    name: Test Golang Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - uses: dominikh/staticcheck-action@v1.2.0
    - uses: arduino/setup-task@v1

    - name: Run Tests
      run: task go:test

    - name: Run Staticcheck
      run: task go:check
